'use client'

import { makeStyles, tokens, typographyStyles } from '@fluentui/react-components'

export const useOverlayStyles = makeStyles({
  shell: {
    position: 'relative',
    width: '100%',
    height: '100%',
    flexGrow: 1,
    minHeight: 0,
  },
  mapRoot: {
    position: 'absolute',
    inset: 0,
  },
  panel: {
    position: 'absolute',
    zIndex: 2,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    boxShadow: tokens.shadow8,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    maxWidth: 'min(510px, calc(100vw - 24px))',
  },
  titlePanel: {
    top: '12px',
    left: '55px',
    '@media (max-width: 720px)': {
      left: '12px',
      top: '12px',
      right: '12px',
      maxWidth: 'none',
    },
  },
  legendPanel: {
    bottom: '25px',
    left: '25px',
    width: 'min(320px, calc(100vw - 50px))',
    fontSize: tokens.fontSizeBase200,
    '@media (max-width: 720px)': {
      bottom: '12px',
      left: '12px',
    },
  },
  controlsStack: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    zIndex: 3,
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    width: 'min(280px, calc(100vw - 24px))',
    '@media (max-width: 720px)': {
      top: 'auto',
      bottom: '120px',
      right: '12px',
      left: 'auto',
    },
  },
  controlCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    boxShadow: tokens.shadow8,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    fontSize: tokens.fontSizeBase200,
  },
  controlHeading: {
    ...typographyStyles.caption1Strong,
    marginTop: 0,
    marginBottom: tokens.spacingVerticalS,
    color: tokens.colorBrandForeground1,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  hint: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    lineHeight: tokens.lineHeightBase100,
    marginTop: '2px',
    marginBottom: '4px',
  },
  layerTip: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    lineHeight: tokens.lineHeightBase100,
    marginLeft: tokens.spacingHorizontalXXL,
    marginBottom: tokens.spacingVerticalXS,
  },
  legendItemStack: {
    marginTop: tokens.spacingVerticalXS,
    marginBottom: tokens.spacingVerticalXS,
  },
  sectionTitle: {
    ...typographyStyles.caption1Strong,
    marginTop: tokens.spacingVerticalXS,
    marginBottom: '2px',
  },
  emphasis: {
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
    marginTop: '3px',
    marginBottom: '3px',
  },
  swatch: {
    width: '12px',
    height: '12px',
    borderRadius: tokens.borderRadiusCircular,
    flexShrink: 0,
  },
  searchResults: {
    listStyleType: 'none',
    marginTop: tokens.spacingVerticalXS,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    padding: 0,
    maxHeight: '180px',
    overflowY: 'auto',
  },
  searchHit: {
    width: '100%',
    justifyContent: 'flex-start',
  },
  popup: {
    fontSize: tokens.fontSizeBase200,
    minWidth: '280px',
    maxWidth: '360px',
    lineHeight: tokens.lineHeightBase200,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    borderRadius: tokens.borderRadiusMedium,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    paddingRight: '28px',
  },
  popupTitle: {
    ...typographyStyles.subtitle2,
    marginTop: 0,
    marginBottom: tokens.spacingVerticalXS,
  },
  popupRow: {
    marginTop: '2px',
    marginBottom: '2px',
  },
  popupMuted: {
    color: tokens.colorNeutralForeground3,
  },
  popupRule: {
    marginTop: tokens.spacingVerticalXS,
    marginBottom: tokens.spacingVerticalXS,
    border: 0,
    borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
  },
  fullscreenBtn: {
    position: 'absolute',
    bottom: '25px',
    right: '12px',
    zIndex: 3,
  },
  status: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    zIndex: 10,
    backgroundColor: tokens.colorNeutralBackground2,
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase400,
    padding: tokens.spacingHorizontalXXL,
    textAlign: 'center',
  },
  statusError: {
    color: tokens.colorPaletteRedForeground1,
  },
})
