const styles = {
  shell: 'map-shell',
  mapRoot: 'map-root',
  panel: 'map-panel',
  titlePanel: 'map-title-panel',
  legendPanel: 'map-legend-panel',
  controlsStack: 'map-controls-stack',
  controlCard: 'map-control-card',
  controlHeading: 'map-control-heading',
  hint: 'map-hint',
  layerTip: 'map-layer-tip',
  legendItemStack: 'map-legend-item-stack',
  sectionTitle: 'map-section-title',
  emphasis: 'map-emphasis',
  legendItem: 'map-legend-item',
  swatch: 'map-swatch',
  searchResults: 'map-search-results',
  searchHit: 'map-search-hit',
  popup: 'map-popup',
  popupTitle: 'map-popup-title',
  popupRow: 'map-popup-row',
  popupMuted: 'map-popup-muted',
  popupRule: 'map-popup-rule',
  fullscreenBtn: 'map-fullscreen-btn',
  status: 'map-status',
  statusError: 'map-status-error',
} as const

export const useOverlayStyles = () => styles